import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "EmberAlert",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-around items-center bg-black h-14 text-white">
          <Link href="/">Home</Link>
	  <Link href="/map">Map</Link>
          <Link href="/impact">Impact</Link>
          <Link href="/top5">Top 5 Wildfires</Link>
        </nav>

        {/* Main Content */}
        <div className="mt-4">
          {children} {/* This renders the content from page.js for the current route */}
        </div>
      </body>
    </html>
  );
}
